/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhysiciansRouteImport } from './routes/physicians'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalReportsRouteImport } from './routes/_authenticated/portal/reports'
import { Route as AuthenticatedPortalPrescriptionsRouteImport } from './routes/_authenticated/portal/prescriptions'
import { Route as AuthenticatedPortalAppointmentsRouteImport } from './routes/_authenticated/portal/appointments'
import { Route as AuthenticatedDoctorAppointmentsRouteImport } from './routes/_authenticated/doctor/appointments'
import { Route as AuthenticatedAdminDoctorsRouteImport } from './routes/_authenticated/admin/doctors'

const PhysiciansRoute = PhysiciansRouteImport.update({
  id: '/physicians',
  path: '/physicians',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/doctor/',
    path: '/doctor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalReportsRoute =
  AuthenticatedPortalReportsRouteImport.update({
    id: '/portal/reports',
    path: '/portal/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPrescriptionsRoute =
  AuthenticatedPortalPrescriptionsRouteImport.update({
    id: '/portal/prescriptions',
    path: '/portal/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAppointmentsRoute =
  AuthenticatedPortalAppointmentsRouteImport.update({
    id: '/portal/appointments',
    path: '/portal/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorAppointmentsRoute =
  AuthenticatedDoctorAppointmentsRouteImport.update({
    id: '/doctor/appointments',
    path: '/doctor/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsRoute =
  AuthenticatedAdminDoctorsRouteImport.update({
    id: '/admin/doctors',
    path: '/admin/doctors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/physicians': typeof PhysiciansRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/physicians': typeof PhysiciansRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/physicians': typeof PhysiciansRoute
  '/_authenticated/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/_authenticated/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/_authenticated/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/_authenticated/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/_authenticated/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/departments'
    | '/physicians'
    | '/admin/doctors'
    | '/doctor/appointments'
    | '/portal/appointments'
    | '/portal/prescriptions'
    | '/portal/reports'
    | '/admin/'
    | '/doctor/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/departments'
    | '/physicians'
    | '/admin/doctors'
    | '/doctor/appointments'
    | '/portal/appointments'
    | '/portal/prescriptions'
    | '/portal/reports'
    | '/admin'
    | '/doctor'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/departments'
    | '/physicians'
    | '/_authenticated/admin/doctors'
    | '/_authenticated/doctor/appointments'
    | '/_authenticated/portal/appointments'
    | '/_authenticated/portal/prescriptions'
    | '/_authenticated/portal/reports'
    | '/_authenticated/admin/'
    | '/_authenticated/doctor/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  PhysiciansRoute: typeof PhysiciansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/physicians': {
      id: '/physicians'
      path: '/physicians'
      fullPath: '/physicians'
      preLoaderRoute: typeof PhysiciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/reports': {
      id: '/_authenticated/portal/reports'
      path: '/portal/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AuthenticatedPortalReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/prescriptions': {
      id: '/_authenticated/portal/prescriptions'
      path: '/portal/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof AuthenticatedPortalPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/appointments': {
      id: '/_authenticated/portal/appointments'
      path: '/portal/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof AuthenticatedPortalAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/appointments': {
      id: '/_authenticated/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AuthenticatedDoctorAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/doctors': {
      id: '/_authenticated/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDoctorsRoute: typeof AuthenticatedAdminDoctorsRoute
  AuthenticatedDoctorAppointmentsRoute: typeof AuthenticatedDoctorAppointmentsRoute
  AuthenticatedPortalAppointmentsRoute: typeof AuthenticatedPortalAppointmentsRoute
  AuthenticatedPortalPrescriptionsRoute: typeof AuthenticatedPortalPrescriptionsRoute
  AuthenticatedPortalReportsRoute: typeof AuthenticatedPortalReportsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDoctorsRoute: AuthenticatedAdminDoctorsRoute,
  AuthenticatedDoctorAppointmentsRoute: AuthenticatedDoctorAppointmentsRoute,
  AuthenticatedPortalAppointmentsRoute: AuthenticatedPortalAppointmentsRoute,
  AuthenticatedPortalPrescriptionsRoute: AuthenticatedPortalPrescriptionsRoute,
  AuthenticatedPortalReportsRoute: AuthenticatedPortalReportsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  PhysiciansRoute: PhysiciansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
